[package]
name = "gwynn-mpkinfo"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
binrw.workspace = true

# Used for decompression
gwynn-mpk = { path = "../mpk" }

[dev-dependencies]
infer = "0.19.0"
md5 = "0.8"
rayon = "1.11.0"
tree_magic_mini = "3.2.0"
