[package]
name = "gwynn-mpk"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
binrw.workspace = true
tracing.workspace = true
flate2 = "1.0.34"
zstd = "0.13.2"
lz4_flex = "0.11.3"
